#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/aefayoub permanent;/" /etc/nginx/sites-available/default
service nginx start
