#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/location \/ {/a \\tlocation \/redirect_me {\\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\\n\t}' /etc/nginx/sites-available/default
service nginx start
