#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i '/server_name _;/a \\n\tlocation \/redirect_me {\\n\t\treturn 301 https:\/\/github.com\/aefayoub;\\n\t}' /etc/nginx/sites-available/default
service nginx start
