#!/usr/bin/env bash
# Script that configures HAproxy in lb-1
apt-get -y update
apt-get -y install haproxy=2.0.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend quotes24.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 379471-web-01 34.207.155.207:80
        server 379471-web-02 52.91.127.229:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
