#!/usr/bin/env bash
# Script that starts nginx
sed -i "s/#user nginx/user ngnix/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
service nginx restart
