#!/usr/bin/env bash
# Script that starts nginx
chmod 777 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-avialable/default
sed -i "s/#user www-datar/user nginx/" /etc/nginx/nginx.conf
pkill -9 apache
sudo nginx -c "service nginx restart"
